# Server Port Configuration
server:
  port: 8888

# Spring Application Name Configuration
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MediHealthOps/medi-health-ops-config
          clone-on-start: true
          search-paths: discovery-service,api-gateway
          default-label: main